"""Render the Markdown draft from the reconciled data.

Plain templating, not an LLM, so the draft only ever shows what was extracted.
"""
from __future__ import annotations

from .schema import (
    CATEGORY_TITLES,
    Category,
    Confidence,
    ReconciliationResult,
    ReconStatus,
)

STATUS_BADGE = {
    ReconStatus.agree: "agree",
    ReconStatus.agree_reworded: "agree (reworded)",
    ReconStatus.conflict: "CONFLICT",
    ReconStatus.only_one: "one source only",
    ReconStatus.inconsistent: "INCONSISTENT",
    ReconStatus.missing: "missing",
}

IMPORTER_TODOS = [
    "Commercial invoice & packing list for the 5 kW order.",
    "Bill of lading / airway bill and a country-of-origin declaration.",
    "The manufacturer's actual compliance/test certificates — the datasheets only "
    "*claim* standards (see conflicts above); request the real CB/CE/IEC test reports.",
    "A photo of the physical product label to confirm model, ratings, manufacturer, "
    "origin and IP rating.",
]


def _cell(v: str | None) -> str:
    return v if v not in (None, "") else "—"


def _esc(s: str | None) -> str:
    return (s or "").replace("|", "\\|").replace("\n", " ").strip()


def render_markdown(result: ReconciliationResult) -> str:
    sids = [s.id for s in result.sources]
    head = "|" + "----|" * (len(sids) + 3)
    L: list[str] = []

    L += [
        "# SunBridge Trading — Draft Compliance Summary (working draft)",
        "",
        f"**Product:** {result.target_model}  ",
        f"**Generated:** {result.generated_at} — auto-generated by pipeline, not hand-written  ",
        "",
        "> Assembled automatically from the manufacturer datasheets below. Every value "
        "is attributed to its source. Where the two sheets disagree, **both** values are "
        "shown — none is chosen or hidden. This is a draft for the import agent, not a "
        "certificate of compliance.",
        "",
        "## Sources",
        "",
        "| ID | Variant (expected / read) | Revision | URL |",
        "|----|----|----|----|",
    ]
    for s in result.sources:
        L.append(
            f"| `{s.id}` | {s.variant_expected or '—'} / {s.variant_detected or '?'} "
            f"| {s.revision_hint or '—'} | {s.url} |"
        )
    L.append("")
    for n in result.notes:
        L += [f"> Note: {n}", ""]

    L += [
        "**Status legend:** agree | agree (reworded) = same meaning, different words | "
        "CONFLICT = sheets disagree | one source only | INCONSISTENT = a sheet "
        "contradicts itself | missing",
        "",
        "## Conflicts & inconsistencies (verify these first)",
        "",
    ]
    flagged = [f for f in result.fields
               if f.status in (ReconStatus.conflict, ReconStatus.inconsistent)]
    if flagged:
        L.append("| Field | " + " | ".join(sids) + " | Issue |")
        L.append("|----|" + "----|" * len(sids) + "----|")
        for f in flagged:
            row = " | ".join(_esc(_cell(f.values.get(s))) for s in sids)
            L.append(f"| **{f.label}** | {row} | {_esc(f.note)} |")
    else:
        L.append("_None detected._")
    L.append("")

    # Per checklist category
    by_cat: dict[Category, list] = {}
    for f in result.fields:
        by_cat.setdefault(f.category, []).append(f)
    for cat in Category:
        fields = by_cat.get(cat, [])
        if not fields:
            continue
        L += [f"## {CATEGORY_TITLES[cat]}", ""]
        L.append("| Field | " + " | ".join(sids) + " | Status | Note |")
        L.append("|----|" + "----|" * len(sids) + "----|----|")
        for f in fields:
            row = " | ".join(_esc(_cell(f.values.get(s))) for s in sids)
            L.append(f"| {f.label} | {row} | {STATUS_BADGE[f.status]} | {_esc(f.note)} |")
        L.append("")

    L += ["## 5. Importer paperwork — SunBridge to supply / chase", ""]
    L += ["_Not derivable from a datasheet; listed so the section isn't silently empty:_", ""]
    L += [f"- [ ] {item}" for item in IMPORTER_TODOS]
    L.append("")

    low = [
        (f.label, s, f.values[s])
        for f in result.fields for s in sids
        if f.values.get(s) and f.confidence.get(s) == Confidence.low
    ]
    L += ["## Provenance & confidence", ""]
    if low:
        L.append("Values the pipeline read with **low confidence** (hard to place in the "
                 "table layout — double-check against the PDF):")
        L.append("")
        for label, s, v in low:
            L.append(f"- **{label}** = `{v}` (from `{s}`)")
    else:
        L.append("No low-confidence values flagged.")
    L += [
        "",
        "---",
        "_Pipeline: fetch → render pages → vision-extract each sheet → reconcile → draft. "
        "Source attribution and confidence for every field are in `output/reconciled.json`._",
    ]
    return "\n".join(L)
